### ISSUE TITLE
Slippage

### ISSUE THREAD

**Issue by andygilb** [Smebra/ADVANCED-Solana-Raydium-Sniping-Bot#11]
What should this be set at in the .env file?

**Comment by Smebra** [comment]
100% is ideal

**Comment by Smebra** [comment]
New Updates:
Fastest Solana Mainnet API Integrated
Advanced Rug Check with Top % Holders & Potential Fake Volume Bundler Detector
Auto Snipe Ongoing Hype Launches
Slippage %

Remove The Previous Versions Completely & Install The New Zip File, & Run The Bot ❤️
