### ISSUE TITLE
Logger 

### ISSUE THREAD

**Issue by azizikheir1** [Smebra/ADVANCED-Solana-Raydium-Sniping-Bot#13]
Hi im trying to run the bot , somehow 
Import logger,retrieveEnviable from ..utils  
in constants 
isnt working

**Comment by azizikheir1** [comment]
Solved, the bot seems to be working well , but doesn't seem to buy pumpfun tokens bonded to ray any idea? Nowadays only pumpfun tokens are really sending

**Comment by Smebra** [comment]
you can snipe them too, figure out the raydium pool these pump fun tokens have when pushed to raydium, and set it as your min pool size, done!

**Comment by Smebra** [comment]
New Updates:
Fastest Solana Mainnet API Integrated
Advanced Rug Check with Top % Holders & Potential Fake Volume Bundler Detector
Auto Snipe Ongoing Hype Launches
Slippage %

Remove The Previous Versions Completely & Install The New Zip File, & Run The Bot ❤️
