### ISSUE TITLE
line 189 - 195

### ISSUE THREAD

**Issue by fuzionplayer** [Smebra/ADVANCED-Solana-Raydium-Sniping-Bot#5]
Quick question why is this rug check function commented out?

**Comment by Smebra** [comment]
We've rolled out a new update, uninstall the entire bot, and re-install from scratch!
all the bugs are fixed
and slippage + rug check options added
and a more advanced sophisticated algorithm for bettee win rates

**Comment by Smebra** [comment]
New Updates:
Fastest Solana Mainnet API Integrated
Advanced Rug Check with Top % Holders & Potential Fake Volume Bundler Detector
Auto Snipe Ongoing Hype Launches
Slippage %

Remove The Previous Versions Completely & Install The New Zip File, & Run The Bot ❤️
