### ISSUE TITLE
error "Error: Non-base58 character"

### ISSUE THREAD

**Issue by strappsdev** [Smebra/ADVANCED-Solana-Raydium-Sniping-Bot#6]
When running the bot, I get the following error: 

/base-x/src/index.js:111
    throw new Error('Non-base' + BASE + ' character')
          
Error: Non-base58 character

I did create the wallet with "solana-keygen new --outfile wallet.json". I've encoded the private key (first 32 bytes) with bs58. I've also added some debug log output at the position where it crashes and the string passed to the decode function looks good.

Any idea how to fix this?

**Comment by Smebra** [comment]
try using a simple phantom wallet, put some sol and convert little to wsol, and use it's private key in the env file, it should work

**Comment by strappsdev** [comment]
That was my initial approach but has resulted in the same error. 
I thought the private key copied from the phantom wallet might be in an different format than base58, therefore I've tried it the other way. I'll give it another try later....

**Comment by Smebra** [comment]
we are launching an update tonight, try installing that, a faster and better version

**Comment by Smebra** [comment]
We've rolled out a new update, uninstall the entire bot, and re-install from scratch!
all the bugs are fixed
and slippage + rug check options added
and a more advanced sophisticated algorithm for bettee win rates

**Comment by strappsdev** [comment]
I did upgrade my checkout and now its working (without any changes to the wallet)! 

Great, thanks!

After some time I keep getting "Server responded with 429 Too Many Requests.  Retrying after ...ms delay" messages. 
Sounds like I'm hitting some rate limit.

I'm on the helius and birdeye free plan. Is it suggested to upgrade to a paid subscription?

**Comment by Smebra** [comment]
yes you can upgrade to a paid version, or just play with the env file and maybe not make the bot perform a lot of actions within a small time frame which might limit you on the free rpc nodes,
if you're going for a paid rpc node, it would work too

**Comment by Smebra** [comment]
New Updates:
Fastest Solana Mainnet API Integrated
Advanced Rug Check with Top % Holders & Potential Fake Volume Bundler Detector
Auto Snipe Ongoing Hype Launches
Slippage %

Remove The Previous Versions Completely & Install The New Zip File, & Run The Bot ❤️
