### ISSUE TITLE
Questions regarding SL and TP

### ISSUE THREAD

**Issue by RidgeGaming** [Smebra/ADVANCED-Solana-Raydium-Sniping-Bot#8]
The bot doesn't tp at the set 20% abut does pull itself out of trades before they rug. if we could get in contact on how you set yours up and the inner workings that would be great!

Thank you!

**Comment by Smebra** [comment]
we just rolled out an update, including rug check and slippage along with more sophisticated algorithm for getting higher win rates! Try installing the bot again!

**Comment by RidgeGaming** [comment]
still my tp and sl is not registering. the bot does work though

**Comment by Smebra** [comment]
did you remove the entire bot, and re-installed from scratch? this latest version? if no, do it...

**Comment by Smebra** [comment]
We've rolled out a new update, uninstall the entire bot, and re-install from scratch!
all the bugs are fixed
and slippage + rug check options added
and a more advanced sophisticated algorithm for better win rates 🐳

**Comment by Smebra** [comment]
New Updates:
Fastest Solana Mainnet API Integrated
Advanced Rug Check with Top % Holders & Potential Fake Volume Bundler Detector
Auto Snipe Ongoing Hype Launches
Slippage %

Remove The Previous Versions Completely & Install The New Zip File, & Run The Bot ❤️
