### ISSUE TITLE
GPRC ?

### ISSUE THREAD

**Issue by RidgeGaming** [Smebra/ADVANCED-Solana-Raydium-Sniping-Bot#9]
Is it possible for me to use a GRPC endpoint for this? if so how would i go about that!

Thanks!

**Comment by RidgeGaming** [comment]
if you have a telegram that'd be awesome!

**Comment by Smebra** [comment]
yea you can use paid rpcs, they will enhance the speed further! but we have rolled out updates and already made the bot much for faster try uninstalling the entire thing and reinstalling from scratch,

and if you have any issues let's address them here? it'll help the other users as well

**Comment by RidgeGaming** [comment]
could you give an example for using the grpc?
a little confused on the birdeye api

**Comment by Smebra** [comment]
New Updates:
Fastest Solana Mainnet API Integrated
Advanced Rug Check with Top % Holders & Potential Fake Volume Bundler Detector
Auto Snipe Ongoing Hype Launches
Slippage %

Remove The Previous Versions Completely & Install The New Zip File, & Run The Bot ❤️
